### ISSUE TITLE
About Uninstall or Remove

### ISSUE THREAD

**Issue by kannagi0303** [kazukikasama/youtube-dlp-gui-installer#2]
Hello again.

When I want to remove it, I have to manually remove it.
Wondering if you would like to offer a removal plan?
Or can you provide instructions for removal in your description?

Thanks

**Comment by kazukikasama** [comment]
i have a uninstall script in the code

**Comment by kannagi0303** [comment]
Pretty sorry I didn't see that earlier.
please don't mind thank you

**Comment by kazukikasama** [comment]
i have https://raw.githubusercontent.com/kazukikasama/youtube-dlp-gui-installer/main/yt-dlp-gui-uninstaller.ps1
I will include the uninstallation in the documentation
