### ISSUE TITLE
FFMPEG link broken?

### ISSUE THREAD

**Issue by s-timm** [kazukikasama/youtube-dlp-gui-installer#3]
Hi!

I think the link to the FFMPEG release is broken. Can it be?

**Comment by kazukikasama** [comment]
Hello i check the link and is ok

**Comment by s-timm** [comment]
Hello! Thanks for your answer!

Yes, today the link is working. Very strange, 2 days ago, it was not working, I got "file not found".

Maybe the link is not always working? 
Look at release page: https://github.com/BtbN/FFmpeg-Builds/releases 

No "Master-Latest..." release on other days (see other "Auto Builds", for example https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-03-23-14-03

Anyway, thanks for your script!
